### ISSUE TITLE
hex data in test cases

### ISSUE THREAD

**Issue by mcr** [AnimaGUS-minerva/voucher#2]
Maybe use new hex input to get test data?
https://github.com/AnimaGUS-minerva/voucher/blob/5da549f0fa307c75c8c8b11d4ae0a8ee2966c383/src/tests.rs#L167

using hex-literal , branch: https://github.com/AnimaGUS-minerva/utils

https://github.com/AnimaGUS-minerva/connect/blob/4d835005ef30ac59f4692019ac428dc472e373a6/src/openswan.rs#L405

**Comment by j-devel** [comment]
Nice!  It works well 9a70181
